name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.1
      - run: bazel build //...
      - run: bazel test --test_output=errors //...
